#! /bin/sh

focus_follows_pointer=$(strawberryc config focus_follows_pointer)
initial_polarity=$(strawberryc config initial_polarity)
automatic_scheme=$(strawberryc config automatic_scheme)
strawberryc config automatic_scheme spiral
strawberryc config initial_polarity first_child
strawberryc config focus_follows_pointer false

cleanup () {
	strawberryc config automatic_scheme "$automatic_scheme"
	strawberryc config initial_polarity "$initial_polarity"
	strawberryc config focus_follows_pointer "$focus_follows_pointer"
}

abort() {
	cleanup
	echo "One test failed." 1>&2
	exit 1
}

echo "Node"
echo "-> Insertion"
./node/insertion || abort
echo "-> Removal"
./node/removal || abort
echo "-> Transfer"
./node/transfer || abort
echo "-> Swap"
./node/swap || abort
echo "-> Flags"
./node/flags || abort
echo "-> Receptacle"
./node/receptacle || abort

echo "Desktop"
echo "-> Transfer"
./desktop/transfer || abort
echo "-> Swap"
./desktop/swap || abort

cleanup

echo "All tests passed."
