#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

strawberryc monitor -d I II III IV V VI VII VIII IX X

strawberryc config border_width         2
strawberryc config window_gap          12

strawberryc config split_ratio          0.52
strawberryc config borderless_monocle   true
strawberryc config gapless_monocle      true

strawberryc rule -a Gimp desktop='^8' state=floating follow=on
strawberryc rule -a Chromium desktop='^2'
strawberryc rule -a mplayer2 state=floating
strawberryc rule -a Kupfer.py focus=on
strawberryc rule -a Screenkey manage=off
