#! /bin/sh

. ./prelude

strawberryc monitor -a "test-swap-a" "test-swap-b"
strawberryc desktop -f "test-swap-a"

window add 5
next_focus_b=$(strawberryc query -N -n @/2/2/1)
strawberryc desktop -f "test-swap-b"
window add 3

strawberryc node -f @test-swap-a:/2/2/1
strawberryc node -a @test-swap-b:/1

strawberryc node @/2 -s @test-swap-b:/1

[ "$(strawberryc query -N -n @test-swap-b:)" = "$next_focus_b" ] || fail "Invalid focus after swap."

window remove 2
strawberryc desktop -f "test-swap-b"
window remove 1 2
window remove 4

strawberryc desktop "test-swap-a" -r
strawberryc desktop "test-swap-b" -r
